# Mengizinkan akses Docker tanpa root
- hosts: all
  become: yes
  tasks:
    - name: docker permission
      command: chmod 666 /var/run/docker.sock

    - name: docker compose permission
      command: chmod +x /usr/bin/docker-compose
