# Feature : Bisa ssh tiap server paswordless, dan connect ke github
# Edit file config dengan server yang diinginkan
# Ubah Private key dan Public Key sesuai yang ada
- hosts: all
  become: yes
  tasks:
  - name: Buat folder .ssh
    file:
      path: /home/rizal/.ssh
      state: directory

  - name: Membuat file known_hosts
    file:
      path: /home/rizal/.ssh/known_hosts
      state: touch

  - name: chown
    command: chown -v rizal /home/rizal/.ssh/known_hosts

  - name: Salin Private Key ke setiap node
    copy:
      src: rizal@dumbways
      dest: /home/rizal/.ssh/rizal@dumbways

  - name: memasukan public key ke authorized_keys dan salin ke setiap node
    copy:
      src: rizal@dumbways.pub
      dest: /home/rizal/.ssh/authorized_keys

  - name: Salin file config ke setiap node
    copy:
      src: config
      dest: /home/rizal/.ssh/config

  - name: hak akses
    command: chmod 666 /home/rizal/.ssh/rizal@dumbways