# Git Clone
- hosts: frontend1
  tasks:
  - name: Clone github
    git:
      repo: git@github.com:awan27/housyfrontend.git
      dest: ~/housyfrontend/
      version: production
      accept_hostkey: yes

  - name: nodejs repo
      apt_repository:
        repo: https://deb.nodesource.com/setup_10.x | sudo -E bash
        state: present

  - name: Install NodeJS
      apt: update_cache=yes name=nodejs state=latest

- hosts: backend
  tasks:
  - name: Clone github
    git:
      repo: git@github.com:awan27/housybackend.git
      dest: ~/housybackend/
      version: production
      accept_hostkey: yes
