- hosts: frontends
  become: true
  tasks:
    - name: start housy-frontend
      command: docker start housy

    - name: start housy-frontend1
      command: docker start housy1

- hosts: backend
  become: true
  tasks:
    - name: start housy-backend
      command: docker start housy
