- hosts: frontends
  become: true
  tasks:
    - name: start housy-frontend
      command: docker start housy

- hosts: backend
  become: true
  tasks:
    - name: start housy-backend
      command: docker start housy
