- hosts: frontend1:backend
  become: yes
  tasks:
  - name: nodejs repo
    apt_repository:
      repo: https://deb.nodesource.com/setup_10.x
      state: present

  - name: Install NodeJS
    apt: update_cache=yes name=nodejs state=latest
