#pakai user rizal !!!
- hosts: frontend1
  tasks:
    - name: Pindah frontend
      command: cd housyfrontend

    - name: Build image
      command: docker buid -t rizal27/housyfront:latest .

    - name: docker push
      command: docker push rizal27/housyfront:latest .

- hosts: backend
  become: true
  tasks:
    - name: Pindah backend
      command: cd housybackend

    - name: Build image
      command: docker buid -t rizal27/housyback:latest .

    - name: docker push
      command: docker push rizal27/housyback:latest .
