#pakai user rizal !!!
- hosts: frontend1
  tasks:
    - name: Build image frontend
      docker_image:
        path: /home/rizal/housyfrontend
        name: rizal27/housyfront:latest

    - name: docker push
      command: docker push rizal27/housyfront:latest .

- hosts: backend
  tasks:
    - name: Build image backend
      docker_image:
        path: /home/rizal/housybackend
        name: rizal27/housyback:latest

    - name: docker push
      command: docker push rizal27/housyback:latest .
