#pakai user rizal !!!
- hosts: frontend1
  tasks:
    - name: Build image frontend
       docker_image:
         path: ~/housyfrontend
         name: rizal27/housyfront
         tag: latest

    - name: docker push
      command: docker push

- hosts: backend
  become: true
  tasks:
    - name: Build image backend
       docker_image:
         path: ~/housybackend
         name: rizal27/housyback
         tag: latest

    - name: docker push
      command: docker push
