- hosts: frontend1
  become: true
  tasks:
    - name: build image
      command: docker build -t rizal27/housyfront:latest .

    - name: docker push
      command: docker push

- hosts: backend
  become: true
  tasks:
    - name: build image
      command: docker build -t rizal27/housyback:latest .

    - name: docker push
      command: docker push
