# Install Docker dan node exporter
- hosts: all
  become: true
  tasks:
    - name: stop node-exporter
      shell: docker stop node-exporter

    - name: hapus
      command: docker rm node-exporter
