# Setup Database => ganti hosts, nama & password mysql_user, dan nama database
- hosts: database
  become: yes
  tasks:
  - name: Install MySQL
    apt:
      name: "{{ item }}"
    with_items:
      - python-mysqldb
      - mysql-server

  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true

  - name: create new user
    mysql_user: 
      name: rizal
      password: duatujuh27 
      priv: '*.*:ALL'
      host: '%'
      state: present

  - name: create database
    mysql_db: 
      name: housy
      state: present

  - name: change bind ip
    lineinfile: 
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: 'bind-address' 
      line: 'bind-address - 0.0.0.0'
      backup: 'yes'
