# Git Clone
- hosts: frontend1
  tasks:
  - name: Clone github
    git:
      repo: git@github.com:awan27/housyfrontend.git
      dest: ~/housyfrontend/
      version: production
      accept_hostkey: yes

- hosts: backend
  tasks:
  - name: Clone github
    git:
      repo: git@github.com:awan27/housybackend.git
      dest: ~/housybackend/
      version: production
      accept_hostkey: yes
