global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.1.4:9100','10.0.1.5:9100','10.0.1.6:9100','10.0.1.7:9100','10.0.1.8:9100','10.0.1.9:9100','10.0.1.10:9100','10.0.0.211:9100']